import NavBar from "@/components/NavBar";
import styles from "@/styles/About.module.css";
import Link from "next/link";
import Head from "next/head";
import graphBar from "@/components/GraphBar";

export default function About() {
    return( 
        <>
            <Head>
                <title>About App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main}`}>
                <graphBar/>
                <NavBar/>
            </main>
        </>
    )
}

