import { createRef, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/index.module.css";
import lottie from "lottie-web";

export default function Home() {
  let animationContainer = createRef();

  useEffect(() => {
    const anim = lottie.loadAnimation({
      container: animationContainer.current,
      rerender: "svg",
      loop: true,
      autoplay: true,
      path: "/animations/data.json",
    });

    return () => anim.destroy();
  }, []);

  const router = useRouter();

  useEffect(() => {
    const timeout = setTimeout(() => {
      router.push("/home");
    }, 8000);

    return () => clearTimeout(timeout);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.logo}>
          <img src="./images/Logo.png" alt="Logo" />
        </div>
        <div className={`${styles.animation__container} ${styles.translate}`}>
          <div className={styles.animation} ref={animationContainer} />
        </div>
      </main>
    </>
  );
}
