import { useEffect, useState } from "react";
import io from "socket.io-client";

let socket;

const Chat = () => {

    const [username,setUsername] = useState("")
    const [message,setMessage] = useState("")
    const [allMessages,setAllMessages] = useState([])

    useEffect(()=> {
    socketInitializer();
},[])

async function socketInitializer() {
    await fetch("/api/socket")

    socket = io();

    socket.on("receive-message",(data)=>{
        console.log(data);
        setAllMessages(pre => [...pre,data]);
    });
}

function handleSubmit(e) {
    e.preventDefault()

    socket.emit("send-message",{
        username,
        message
    })
}

return(
    <div>
        <h1>Live Chat</h1>
        <p>Enter a username</p>
        <input value ={username} onChange={(e) => setUsername(e.target.value)} />

        <br />
        <br />

       {!!username &&(
        <div>
        {allMessages.map(({ username, message }, index) => (
          <p key={index}>
            {username}: {message}
          </p>
        ))}

        <br />

            <form onSubmit={handleSubmit}>
                <input name="message" value={message} onChange={(e)=> setMessage(e.target.value)} />
            </form>
        </div>
        )}
    </div>
)
};

export default Chat;


/*import Head from "next/head";
import styles from "@/styles/livechat.module.css";

export default function Chat() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="chat-container">
          <div className="chat-messages" id="chat-messages"></div>
          <form>
            <input type="text" className="chat-input" id="message-input" placeholder="Type your message..."></input>
            <button type="submit" className="chat-button">Send</button>
          </form>
        </div>
      </main>
    </>
  );
}*/
